### PR TITLE
Fixed timout issue

### PR DESCRIPTION
**Pull request by lord-ne**
See https://github.com/sttz/expresso/pull/10#issuecomment-860148102

### CODE REVIEW

**Comment by Tetsukick** [comment]
@sttz   
I faced same issue.
please approve this PR and please release new version.

**Comment by sttz** [comment]
Thanks! Released version 1.2.1 with the change.

**Comment by lord-ne** [comment]
Can confirm 1.2.1 Windows build is working.

**Comment by Tetsukick** [comment]
@sttz @lord-ne 
Thank you for your efforts!!

**Pull request merged**
